config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'shopping_trips#index'

  resources :shopping_trips
  resources :items
  resources :shopping_lists
  resources :shopping_list_items

  get 'adminshow', to:  'shopping_list_items#adminshow'
  get 'admin_checkbox', to:  'shopping_list_items#admin_checkbox'
  get 'tally', to:  'shopping_list_items#tally'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  belongs_to :shopping_trip
  has_many :shopping_list_items
end

app/models/shopping_list_item.rb
class ShoppingListItem < ApplicationRecord
  # belongs_to :item
  belongs_to :shopping_list
  has_many :items
end

app/models/shopping_trip.rb
class ShoppingTrip < ApplicationRecord
  # belongs_to :shopping_list
  has_many :shopping_lists
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true
  devise :database_authenticatable, :authentication_keys => [:username]

  validates :email, :uniqueness => {:allow_blank => true}


  has_many :shopping_lists
  has_many :shopping_list_items, through: :shopping_lists

  def email_required?
    false
  end

  def will_save_change_to_email?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/shopping_list_items_controller.rb
class ShoppingListItemsController < ApplicationController

  protect_from_forgery except: :adminshow

  def index

  end

  def show
    @shopping_trip = ShoppingTrip.find(params[:id])
    @shopping_list = @shopping_trip.shopping_lists.where(user: current_user)
    if @shopping_list.first
      @all_items = @shopping_list.first.shopping_list_items.order('updated_at DESC')
    else
      @all_items = []
    end

    if @shopping_trip.shopping_lists.where(user: current_user).size > 0
      @shopping_list = @shopping_trip.shopping_lists.where(user: current_user).first
    else
      @shopping_list = ShoppingList.new
      @shopping_list.user = current_user
      @shopping_list.shopping_trip = @shopping_trip
      @shopping_list.save
    end

    @shopping_list_items  = ShoppingListItem.new
  end

  def adminshow
    @shopping_trip = ShoppingTrip.find(params[:format])
    @full_shop = []
    @shopping_trip.shopping_lists.each do |shopping_list|
      @full_shop << shopping_list.shopping_list_items
    end
    @full_shop.flatten!
    @full_shop = @full_shop.sort_by {|obj| obj.name.capitalize}
  end

  def admin_checkbox
    item = ShoppingListItem.find(params[:item_id])
    done = params[:item_done] == "true"
    item.done = !done
    item.save
  end

  def create
    @shopping_list = ShoppingList.find(params[:shopping_list_id])
    params[:shopping_list_item]["item_ids"].each do |item_id|
      if !item_id.empty?
        if !Item.where(id: item_id.to_i).empty?
          item = Item.where(id: item_id.to_i).first
        else
          item = Item.new(name: item_id)
          item.save
        end
        shopping_list_item = ShoppingListItem.new
        shopping_list_item.name = item.name
        shopping_list_item.quantity  = params[:shopping_list_item]["quantity"]
        shopping_list_item.quantity = shopping_list_item.quantity.empty? ? nil : shopping_list_item.quantity
        shopping_list_item.shopping_list = @shopping_list
        shopping_list_item.save
      end
    end
    redirect_to shopping_list_item_path(@shopping_list.shopping_trip)
  end

  def edit
    @shopping_trip = ShoppingTrip.find(params[:id])
    @full_shop = []
    @shopping_trip.shopping_lists.each do |shopping_list|
      @full_shop << shopping_list.shopping_list_items
    end
    @full_shop.flatten!
    @full_shop = @full_shop.sort_by {|obj| obj.name.capitalize}
  end

  def update
    shopping_list_item = ShoppingListItem.find(params[:id])
    shopping_list_item.price = params[:shopping_list_item][:price].to_f*100.0
    shopping_list_item.save
  end


  def destroy
    item = ShoppingListItem.find(params[:id])
    item.destroy
  end

end

app/controllers/shopping_trips_controller.rb
class ShoppingTripsController < ApplicationController

  def index
    @shopping_trips = ShoppingTrip.all
  end

  def new
    @shopping_trip = ShoppingTrip.new
  end

  def create
    @shopping_trip = ShoppingTrip.new(shopping_trip_params)
    if @shopping_trip.save
      redirect_to root_path
    else
      raise
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def shopping_trip_params
    params.require(:shopping_trip).permit(:date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Kealy Shopping</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('shoppingcart.jpg') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<%# if notice %>
  <!-- <div class="alert alert-info alert-dismissible fade show m-1" role="alert"> -->
    <%#= notice %>
    <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"> -->
      <!-- <span aria-hidden="true">&times;</span> -->
    <!-- </button> -->
  <!-- </div> -->
<%# end %>
<%# if alert %>
  <!-- <div class="alert alert-warning alert-dismissible fade show m-1" role="alert"> -->
    <%#= alert %>
    <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close"> -->
      <!-- <span aria-hidden="true">&times;</span> -->
    <!-- </button> -->
  <!-- </div> -->
<%# end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "shoppingcart.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <span class="p-2">Logged in as <%= current_user.username %></span>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "shoppingcart.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shopping_list_items/adminshow.html.erb
<div class="container">

  <h1 style="text-align: center">Full Shopping list for <strong><%= @shopping_trip.date.strftime("%A, %d %b") %></strong></h1>

  <div class="display-list">
    <ul>
      <% @full_shop.each do |item| %>
        <li>
          <%= item.name %>

          <% if !item.quantity.nil?  %>
            – <%= item.quantity %>
          <% end %>
          <span style="opacity: 0.3">(<%= item.shopping_list.user.username[0..1].capitalize %>)</span>
          <%= link_to admin_checkbox_path(item_id: item.id, item_done: item.done), remote: true do %>
            <% if item.done %>
              <i class="checkmark fas fa-check-circle checked"></i>
            <% else %>
              <i class="checkmark fas fa-check-circle"></i>
            <% end %>
          <% end %>

        </li>
      <% end %>
    </ul>
  </div>

  <%= link_to 'Tally', edit_shopping_list_item_path(@shopping_trip), class: "btn btn-primary" %>

</div>


<script>
  Array.from(document.getElementsByClassName("checkmark")).forEach(function(item) {
     item.addEventListener('click', function() {
       item.classList.toggle("checked");
     })
  });
</script>

app/views/shopping_list_items/edit.html.erb
<div class="container">

  <h1>Add pricing and Tally</h1>

  <% @full_shop = @full_shop.sort_by {|obj| obj.name.capitalize}  %>
  <% @full_shop = @full_shop.select {|obj| obj.done}  %>

  <% @full_shop.each do |item| %>
    <%= simple_form_for item, html: { class: "d-flex justify-content-end"} do |f| %>
      <span class="tally-form-text"> <%= item.name %> <% if item.quantity %>(<%= item.quantity %>) <% end %> [<%= item.shopping_list.user.username %>]</span>
      €<%= f.input :price, label: false, placeholder: " Enter price in euro", class: "align-self-center" %>
      <%= f.submit "Update", class: "btn btn-primary fuckyou" %>
    <% end %>
  <% end %>



  <% User.all.each do |user| %>
    <div class="totals-card">
      <h2><%= user.username.capitalize %>'s Total</h2>
      <% total = 0 %>
      <% not_priced = [] %>
      <ul>
        <% @full_shop.each do |shopping_list_item|  %>
          <% if shopping_list_item.shopping_list.user.username == user.username %>
            <li>
              <%= shopping_list_item.name %> €<%= shopping_list_item.price.to_f/100 %>
            </li>
            <% if shopping_list_item.price %>
              <% total += shopping_list_item.price  %>
            <% else %>
              <% not_priced << shopping_list_item.name %>
            <% end %>
          <% end %>
        <% end %>
      </ul>
      <hr>
      <span><strong><%= user.username.capitalize %>'s total: €<%= total/100.0 %></strong></span>
      <br>
      <span><%= not_priced.size %> items were not priced</span>
      <%= not_priced %>
      <br>
      <br>
    </div>
  <% end %>

<style>
  .fuckyou {
    width: 150px;
    height: 38px;
  }
</style>


</div>

app/views/shopping_list_items/show.html.erb
<div class="container">
  <h1><strong><%= current_user.username.capitalize %>'s </strong>  items for the shop on <strong><%= @shopping_trip.date.strftime("%A, %d %b") %></strong></h1>

   <br><br><br>

  <%= simple_form_for @shopping_list_items do |f| %>
    <%= f.association :items , label: "Select one or more grocery items and click 'add to shopping list'  ", class: "select2", input_html: {multiple: true, class: "select2"} %>
    <%= hidden_field_tag 'shopping_list_id', @shopping_list.id %>
    <%= f.input :quantity, label: "Quantity (optional)", placeholder: "6 of, 1 litre of, 500kg, etc..." %>

    <%= f.submit "Add to shopping list", class: "btn w-100 btn-primary" %>
  <% end %>

  <br><br>

  <h3 style="margin: 30px auto 5px auto; text-align: center;">Your items</h3>

  <div class="display-list">
    <ul>
      <% @all_items.each do |item| %>
        <li>
          <%= item.name %>
          <% if !item.quantity.nil?  %>
           (<%= item.quantity %>)
          <% end %>

          <%= link_to shopping_list_item_path(item), method: :delete, remote: true, class: "removal" do %>
            <i style="color:red;" class="fas fa-times"></i>
          <% end %>

        </li>
      <% end %>
    </ul>
  </div>

  <br><br><br>
</div>

<script>
  Array.from(document.getElementsByClassName("removal")).forEach(function(item) {
     item.addEventListener('click', function() {
       item.parentElement.classList.add("d-none")
     })
  });
</script>

app/views/shopping_trips/index.html.erb
<div class="container">


  <h1>Upcoming shopping trips</h1>
  <% @shopping_trips.where("date >= ?", Time.now - 24*60*60).each do |shopping_trip| %>
    <% if current_user.username == "admin" %>
      <div class="card"> <%= link_to shopping_trip.date.strftime("%A, %d %b"), adminshow_path(shopping_trip) %> </div>
    <% else %>
      <div class="card"> <%= link_to shopping_trip.date.strftime("%A, %d %b"), shopping_list_item_path(shopping_trip) %> </div>
    <% end %>
  <% end %>

  <% if current_user.username == "admin" %>
    <%= link_to 'Create a New shopping trip', new_shopping_trip_path %>
  <% end %>

  <% @shopping_trips.where("date < ?", Time.now - 24*60*60).each do |shopping_trip| %>
    <br><br><br>
    <h1>Past shopping Trips</h1>
    <% if current_user.username == "admin" %>
      <div class="card"> <%= link_to shopping_trip.date.strftime("%A, %d %b"), adminshow_path(shopping_trip) %> </div>
    <% end %>
  <% end %>

  <!-- <h1 style="opacity: 0.3">Past shopping trips</h1> -->
  <%# @shopping_trips.where("date <= ?", Time.now).each do |shopping_trip| %>
    <!-- <div class="card"  style="opacity: 0.5"> <%#= link_to shopping_trip.date.strftime("%A, %d %b"), shopping_list_item_path(shopping_trip) %> </div> -->
  <%# end %>

  <div class="thefooter">
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
  </div>

</div>

app/views/shopping_trips/new.html.erb
<div class="container">
  New shopping trip
  <%= simple_form_for @shopping_trip do |f| %>
    <%= f.input :date %>
    <%= f.submit "Add", class: "btn btn-primary" %>
  <% end %>
</div>